name: Lint

on: [pull_request]

jobs:
  review:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Lint Project
        uses: reviewdog/action-golangci-lint@v2
        with:
          reporter: github-pr-review
